### ISSUE TITLE
Add real example [Guide] to README

### ISSUE THREAD

**Issue by MahmoudMabrok** [TheOnlyTails/ketex#1]
as current documentation, is API doc. 
could we have a guide with examples.

**Comment by TheOnlyTails** [comment]
I'm on vacation right now, but I'm definitely planning on it once I get back.

**Comment by MahmoudMabrok** [comment]
happy vacation.

**Comment by TheOnlyTails** [comment]
I'm tracking progress on this in the following [discussion](https://github.com/theonlytails/ketex/discussions/2).
